version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: forestation_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /c/Users/roble/Documents/forestation_proyect:/forestation_proyect

volumes:
  pgdata:
